config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#show', id: 'home'

  devise_for :users, controllers: {
    sessions: "sessions",
    registrations: "registrations"
  }

  resources :players, except: [:new, :create, :destroy] do
    member do
      get :raiding
      get :positions
    end

    resources :cities do
      resources :raids
      resources :scouts
    end
  end

  namespace :api, defaults: {format: 'json'} do
    resources :players, only: [:show] do
      resources :cities, except: [:new, :edit]  do
        resources :raids, except: [:new, :edit]
        resources :scouts, except: [:new, :edit]
      end
    end
  end
end

app/models/raid.rb
class Raid < ActiveRecord::Base
  belongs_to :city

  validates :city,      presence: true
  validates :timber,    presence: true, numericality: {only_integer: true}
  validates :bronze,    presence: true, numericality: {only_integer: true}
  validates :food,      presence: true, numericality: {only_integer: true}
  validates :capacity,  presence: true, numericality: {only_integer: true}
  validates :reported_at, presence: true

  after_create do
    # FIXME Move this into RaidsController#create
    city.update(last_battle_reported_at: reported_at)
  end

  before_create :calculate_expires_at

  def self.last_week
    where('reported_at > ?', Time.now - 1.week)
  end
  
  def resources
    timber + bronze + food
  end

  def at_capacity?
    resources > (capacity * 0.95 - 1).round(0)
  end

  private

  def calculate_expires_at
    self.expires_at = reported_at.utc.midnight + 7.days
  end
end

app/controllers/api/raids_controller.rb
module Api
  class RaidsController < BaseController
    before_action :load_player
    before_action :load_city

    def index
      @raids = @city.raids
    end

    def show
      @raid = @city.raids.find params[:id]
    end

    def create
      @raid = @city.raids.build raid_params

      if @raid.save
        render :show, status: :created, location: [:api, @player, @city, @raid]
      else
        render json: {errors: @raid.errors}, status: :unprocessable_entity
      end
    end

    def update
      @raid = @city.raids.find params[:id]

      if @raid.update raid_params
        render :show, location: [:api, @player, @city, @raid]
      else
        render json: {errors: @raid.errors}, status: :unprocessable_entity
      end
    end

    def destroy
      @raid = @city.raids.find params[:id]
      @raid.destroy!
      render nothing: true, status: :no_content
    end

    private

    def load_player
      @player = Player.find params[:player_id]
    end

    def load_city
      @city = @player.cities.find params[:city_id]
    end

    def raid_params
      params.require(:raid).permit(:timber, :bronze, :food, :capacity, :reported_at)
    end
  end
end

app/controllers/raids_controller.rb
class RaidsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_player
  before_action :set_city
  before_action :set_raid, only: [:show, :edit, :update, :destroy]

  # GET /raids
  # GET /raids.json
  def index
    @raids = @city.raids
  end

  # GET /raids/1
  # GET /raids/1.json
  def show
  end

  # GET /raids/new
  def new
    @raid = @city.raids.build
  end

  # GET /raids/1/edit
  def edit
  end

  # POST /raids
  # POST /raids.json
  def create
    @raid = @city.raids.build(raid_params)

    respond_to do |format|
      if @raid.save
        format.html { redirect_to [:raiding, @player], notice: 'Raid was successfully created.' }
        format.json { render :show, status: :created, location: [@player, @city] }
      else
        format.html { render :new }
        format.json { render json: @raid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /raids/1
  # PATCH/PUT /raids/1.json
  def update
    respond_to do |format|
      if @raid.update(raid_params)
        format.html { redirect_to [@player, @city], notice: 'Raid was successfully updated.' }
        format.json { render :show, status: :ok, location: [@player, @city] }
      else
        format.html { render :edit }
        format.json { render json: @raid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /raids/1
  # DELETE /raids/1.json
  def destroy
    @raid.destroy
    respond_to do |format|
      format.html { redirect_to [@player, @city], notice: 'Raid was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_raid
      @raid = @city.raids.find(params[:id])
    end

    def set_player
      @player = Player.find(params[:player_id])
    end

    def set_city
      @city = @player.cities.find(params[:city_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def raid_params
      params.require(:raid).permit(:timber, :bronze, :food, :capacity, :reported_at)
    end
end

app/views/raids/_form.html.erb
<%= form_for([@player, @city, @raid], role: 'form') do |f| %>
  <% if @raid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@raid.errors.count, "error") %> prohibited this raid from being saved:</h2>

      <ul>
      <% @raid.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :timber %>
    <%= f.number_field :timber, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :bronze %>
    <%= f.number_field :bronze, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :food %>
    <%= f.number_field :food, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :capacity %>
    <%= f.number_field :capacity, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :reported_at %>
    <%= f.datetime_picker :reported_at, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit 'Save', class: 'btn btn-default' %>
    <small><%= link_to 'Cancel', player_city_path(@player, @city) %></small>
  </div>
<% end %>

app/views/raids/_table.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Raid Reports
    <%= link_to 'New Raid Report', [:new, @player, @city, :raid], class: 'btn btn-success pull-right' %>
    <div class="clearfix"></div>
  </div>
  <table class="table table-condensed">
    <thead>
      <tr>
        <th>Timber</th>
        <th>Bronze</th>
        <th>Food</th>
        <th>Total</th>
        <th>Capacity</th>
        <th>Report Time</th>
        <th>Expires At</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% if @raids.none? %>
        <tr colspan="8">
          <td>No raid reports found.</td>
        </tr>
      <% end %>
      <% @raids.each do |raid| %>
        <tr>
          <td><%= raid.timber_number %></td>
          <td><%= raid.bronze_number %></td>
          <td><%= raid.food_number %></td>
          <td><%= raid.total_resources %></td>
          <td><%= raid.capacity %> (<%= raid.capacity_pct %>)</td>
          <td><%= raid.report_datetime %></td>
          <td><%= raid.expiry_datetime %></td>
          <td>
            <%= link_to icon('edit'), edit_player_city_raid_path(@player, @city, raid) %>
          </td>
          <td>
            <%= link_to icon('delete'), [@player, @city, raid], method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/raids/edit.html.erb
<%= form_wrapper "Edit raid report for #{@city.name}", size: 'large' do %>
  <%= render 'form' %>
<% end %>

app/views/raids/index.html.erb
<h1>Listing raids</h1>

<%= link_to 'Player', [@player] %> |
<%= link_to 'City', [@player, @city] %> |
<%= link_to 'New Raid', [:new, @player, @city, :raid] %>
<br>
<table>
  <thead>
    <tr>
      <td>Timber</td>
      <td>Bronze</td>
      <td>Food</td>
      <td>Total</td>
      <td>Capacity</td>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @raids.each do |raid| %>
      <tr>
        <td><%= raid.timber %></td>
        <td><%= raid.bronze %></td>
        <td><%= raid.food %></td>
        <td><%= raid.total_resources %></td>
        <td><%= raid.capacity %> (<%= raid.capacity_pct %>%)</td>
        <td><%= link_to 'Edit', edit_player_city_raid_path(@player, @city, raid) %></td>
        <td><%= link_to 'Destroy', [@player, @city, raid], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/raids/new.html.erb
<%= form_wrapper "New raid report for #{@city.name}", size: 'large' do %>
  <%= render 'form' %>
<% end %>

app/views/raids/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_raid_path(@raid) %> |
<%= link_to 'Back', raids_path %>