config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#show', id: 'home'

  devise_for :users, controllers: {
    sessions: "sessions",
    registrations: "registrations"
  }

  resources :players, except: [:new, :create, :destroy] do
    member do
      get :raiding
      get :positions
    end

    resources :cities do
      resources :raids
      resources :scouts
    end
  end

  namespace :api, defaults: {format: 'json'} do
    resources :players, only: [:show] do
      resources :cities, except: [:new, :edit]  do
        resources :raids, except: [:new, :edit]
        resources :scouts, except: [:new, :edit]
      end
    end
  end
end

app/models/scout.rb
class Scout < ActiveRecord::Base
  belongs_to :city

  validates :city,       presence: true
  validates :timber,     presence: true, numericality: {only_integer: true}
  validates :bronze,     presence: true, numericality: {only_integer: true}
  validates :food,       presence: true, numericality: {only_integer: true}
  validates :reported_at, presence: true

  after_create do
    city.update(last_battle_reported_at: reported_at)
  end
end

app/controllers/api/scouts_controller.rb
module Api
  class ScoutsController < BaseController
    before_action :load_player
    before_action :load_city

    def index
      @scouts = @city.scouts
    end

    def show
      @scout = @city.scouts.find params[:id]
    end

    def create
      @scout = @city.scouts.build scout_params

      if @scout.save
        render :show, status: :created, location: [:api, @player, @city, @scout]
      else
        render json: {errors: @scout.errors}, status: :unprocessable_entity
      end
    end

    def update
      @scout = @city.scouts.find params[:id]

      if @scout.update scout_params
        render :show, location: [:api, @player, @city, @scout]
      else
        render json: {errors: @scout.errors}, status: :unprocessable_entity
      end
    end

    def destroy
      @scout = @city.scouts.find params[:id]
      @scout.destroy!
      render nothing: true, status: :no_content
    end

    private

    def load_player
      @player = Player.find params[:player_id]
    end

    def load_city
      @city = @player.cities.find params[:city_id]
    end

    def scout_params
      params.require(:scout).permit(:timber, :bronze, :food, :reported_at)
    end
  end
end

app/controllers/scouts_controller.rb
class ScoutsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_player
  before_action :set_city
  before_action :set_scout, only: [:show, :edit, :update, :destroy]

  # GET /scouts
  # GET /scouts.json
  def index
    @scouts = @city.scouts
  end

  # GET /scouts/1
  # GET /scouts/1.json
  def show
  end

  # GET /scouts/new
  def new
    @scout = @city.scouts.build
  end

  # GET /scouts/1/edit
  def edit
  end

  # POST /scouts
  # POST /scouts.json
  def create
    @scout = @city.scouts.build(scout_params)

    respond_to do |format|
      if @scout.save
        format.html { redirect_to [:raiding, @player], notice: 'Scout was successfully created.' }
        format.json { render :show, status: :created, location: [@player, @city] }
      else
        format.html { render :new }
        format.json { render json: @scout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scouts/1
  # PATCH/PUT /scouts/1.json
  def update
    respond_to do |format|
      if @scout.update(scout_params)
        format.html { redirect_to [@player, @city], notice: 'Scout was successfully updated.' }
        format.json { render :show, status: :ok, location: [@player, @city] }
      else
        format.html { render :edit }
        format.json { render json: @scout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scouts/1
  # DELETE /scouts/1.json
  def destroy
    @scout.destroy
    respond_to do |format|
      format.html { redirect_to [@player, @city], notice: 'Scout was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scout
      @scout = Scout.find(params[:id])
    end

    def set_player
      @player = Player.find(params[:player_id])
    end

    def set_city
      @city = @player.cities.find(params[:city_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scout_params
      params.require(:scout).permit(:timber, :bronze, :food, :reported_at)
    end
end

app/views/scouts/_form.html.erb
<%= form_for([@player, @city, @scout], role: 'form') do |f| %>
  <% if @scout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scout.errors.count, "error") %> prohibited this scout from being saved:</h2>

      <ul>
      <% @scout.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :timber %>
    <%= f.number_field :timber, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :bronze %>
    <%= f.number_field :bronze, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :food %>
    <%= f.number_field :food, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :reported_at %>
    <%= f.datetime_picker :reported_at, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit 'Save', class: 'btn btn-default' %>
    <small><%= link_to 'Cancel', player_city_path(@player, @city) %></small>
  </div>
<% end %>

app/views/scouts/_table.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Scout Reports
    <%= link_to 'New Scout Report', [:new, @player, @city, :scout], class: 'btn btn-success pull-right' %>
    <div class="clearfix"></div>
  </div>
  <table class="table table-condensed">
    <thead>
      <tr>
        <th>Timber</th>
        <th>Bronze</th>
        <th>Food</th>
        <th>Total</th>
        <th>Report Time</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% if @scouts.none? %>
        <tr colspan="8">
          <td>No scout reports found.</td>
        </tr>
      <% end %>
      <% @scouts.each do |scout| %>
        <tr>
          <td><%= scout.timber_number %></td>
          <td><%= scout.bronze_number %></td>
          <td><%= scout.food_number %></td>
          <td><%= scout.total_resources %></td>
          <td><%= scout.report_datetime %></td>
          <td>
            <%= link_to icon('edit'), edit_player_city_scout_path(@player, @city, scout) %>
          </td>
          <td>
            <%= link_to icon('delete'), [@player, @city, scout], method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/scouts/edit.html.erb
<%= form_wrapper "Edit scout report for #{@city.name}", size: 'large' do %>
  <%= render 'form' %>
<% end %>

app/views/scouts/index.html.erb
<h1>Listing scouts</h1>

<%= link_to 'Player', [@player] %> |
<%= link_to 'City', [@player, @city] %> |
<%= link_to 'New Scout', [:new, @player, @city, :scout] %>
<br />
<table>
  <thead>
    <tr>
      <th>Timber</th>
      <th>Bronze</th>
      <th>Food</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scouts.each do |scout| %>
      <tr>
        <td><%= scout.timber %></td>
        <td><%= scout.bronze %></td>
        <td><%= scout.food %></td>
        <td><%= scout.total_resources %></td>
        <td><%= link_to 'Edit', edit_player_city_scout_path(@player, @city, scout) %></td>
        <td><%= link_to 'Destroy', [@player, @city, scout], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/scouts/new.html.erb
<%= form_wrapper "New scout report for #{@city.name}", size: 'large' do %>
  <%= render 'form' %>
<% end %>

app/views/scouts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_scout_path(@scout) %> |
<%= link_to 'Back', scouts_path %>