config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#show', id: 'home'

  devise_for :users, controllers: {
    sessions: "sessions",
    registrations: "registrations"
  }

  resources :players, except: [:new, :create, :destroy] do
    member do
      get :raiding
      get :positions
    end

    resources :cities do
      resources :raids
      resources :scouts
    end
  end

  namespace :api, defaults: {format: 'json'} do
    resources :players, only: [:show] do
      resources :cities, except: [:new, :edit]  do
        resources :raids, except: [:new, :edit]
        resources :scouts, except: [:new, :edit]
      end
    end
  end
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :user
  has_many :cities
  has_many :raids, through: 'cities'
  has_many :scouts, through: 'cities'

  validates :name, presence: true

  def coordinates
    Coordinates.new(x, y)
  end
end

app/controllers/api/players_controller.rb
module Api
  class PlayersController < BaseController
    def show
      @player = Player.find params[:id]
    end
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_player, except: [:index]

  # GET /players
  # GET /players.json
  def index
    authorize! :index, Player
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
    authorize! :show, @player
  end

  def raiding
    @cities = @player.cities.includes(:raids, :scouts).decorate
    @cities = @cities.sort {|a,b| a.last_battle_reported_at <=> b.last_battle_reported_at}.reverse
  end

  def positions
  end

  # GET /players/1/edit
  def edit
    authorize! :edit, @player
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    authorize! :update, @player

    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name, :timezone, :x, :y)
    end
end

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <%= label_tag :coordinates %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :x %>
        <%= f.text_field :x, class: 'form-control' %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :y %>
        <%= f.text_field :y, class: 'form-control' %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <%= f.label :timezone, 'Time Zone' %>
        <%= f.time_zone_select :timezone %>
      </div>
    </div>
  </div>
  <%= f.submit 'Save' %>
<% end %>

app/views/players/edit.html.erb
<%= form_wrapper 'Editing player', size: 'small' do %>
  <%= render 'form' %>
<% end %>

app/views/players/index.html.erb
<h1>Listing players</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<%= form_wrapper 'New player', size: 'small' do %>
  <%= render 'form' %>
<% end %>

app/views/players/positions.html.erb
<h2>
  <%= @player.name %>
  <small><%= link_to icon('edit'), edit_player_path(@player) %></small>
</h2>

<div class="row">
  <div class="col-md-3">
    <h3>Current Troops</h3>

    <% %w(offense defense).each do |type| %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= type.humanize %></h3>
      </div>
      <table class="table table-condensed" data-type="<%= type %>">
        <thead>
          <tr>
            <th>Unit</th>
            <th>Qty</th>
            <th>RValue</th>
          </tr>
        </thead>
        <tbody>
          <% Unit.send(type).each do |unit| %>
          <tr>
            <td title="<%= unit.name %>"><%= unit.initials %></td>
            <td><input min="0" max="99999" class="rvalue-qty form-control input-sm" type="number" data-target="<%= unit.id %>-rvalue" /></td>
            <td><span class="rvalue pull-right" id="<%= unit.id %>-rvalue" data-rvalue="<%= unit.rvalue %>"></span></td>
          </tr>
          <% end %>
          <tr>
            <td colspan="2">Total RValue</td>
            <td><span class="pull-right" id="total-<%= type %>-rvalue"></span></td>
          </tr>
        </tbody>
      </table>
    </div>
    <% end %>
  </div>

  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Persian Position</h3>
      </div>
      <table class="table table-condensed">
        <thead>
          <tr>
            <td>Cavalry</td>
            <td>Phalanx</td>
            <td>Heavy</td>
            <td>Light</td>
            <td>Power</td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><input min="0" max="99999" class="pp-qty" type="number" data-name="pp-cavalry" data-power="80" /></td>
            <td><input min="0" max="99999" class="pp-qty" type="number" data-name="pp-phalanx" data-power="60" /></td>
            <td><input min="0" max="99999" class="pp-qty" type="number" data-name="pp-heavy" data-power="40" /></td>
            <td><input min="0" max="99999" class="pp-qty" type="number" data-name="pp-light" data-power="20" /></td>
            <td><span id="pp-power"></span></td>
          </tr>
          <tr>
            <td><span id="pp-cavalry-pct"></span></td>
            <td><span id="pp-phalanx-pct"></span></td>
            <td><span id="pp-heavy-pct"></span></td>
            <td><span id="pp-light-pct"></span></td>
            <td></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div class="col-md-3">
  </div>
</div>

app/views/players/raiding.html.erb
<br />
<h2>
  <%= @player.name %>
  <small>
    <%= link_to icon('edit'), edit_player_path(@player) %>
  </small>
</h2>

<%= render 'shared/modal' %>

<div class="row">
  <div class="col-md-12">
    <%= render 'cities/table' %>
  </div>
</div>

app/views/players/show.html.erb
<br />
<h2>
  <%= @player.name %>
  <small>
    <%= link_to icon('edit'), edit_player_path(@player) %>
  </small>
</h2>

<%= render 'shared/modal' %>

<div class="row">
  <div class="col-md-12">
    <%= render 'cities/table' %>
  </div>
</div>