config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#show', id: 'home'

  devise_for :users, controllers: {
    sessions: "sessions",
    registrations: "registrations"
  }

  resources :players, except: [:new, :create, :destroy] do
    member do
      get :raiding
      get :positions
    end

    resources :cities do
      resources :raids
      resources :scouts
    end
  end

  namespace :api, defaults: {format: 'json'} do
    resources :players, only: [:show] do
      resources :cities, except: [:new, :edit]  do
        resources :raids, except: [:new, :edit]
        resources :scouts, except: [:new, :edit]
      end
    end
  end
end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :player
  has_many :raids,  -> { order(:reported_at => :desc) }
  has_many :scouts, -> { order(:reported_at => :desc) }
  has_many :level_progresses

  validates :name, presence: true

  after_commit :track_level_progress

  def self.active
    last_report_within 7.days
  end

  def self.last_report_within(time)
    includes(:scouts, :raids).references(:scouts, :raids)
      .where('raids.reported_at > :time OR scouts.reported_at > :time', time: time.ago).uniq
  end

  def coordinates
    Coordinates.new(x,y)
  end

  def current_resources(kind)
    ResourceEstimator.new(self, kind).estimate
  end

  def estimated_raid_resources
    return nil unless acropolis

    t = current_resources(:timber)
    b = current_resources(:bronze)
    f = current_resources(:food)
    return nil unless t && b && f

    t = [0, t - acropolis].max
    b = [0, b - acropolis].max
    f = [0, f - acropolis].max
    t + b + f
  end

  def last_battle_report
    last_raid = raids.first
    last_scout = scouts.first
    return nil unless last_raid || last_scout
    return last_scout unless last_raid
    return last_raid unless last_scout
    last_raid.reported_at > last_scout.reported_at ? last_raid : last_scout
  end

private

  def track_level_progress
    if level_progresses.empty? || level_progresses.last.level < level
      level_progresses.create!(level: level)
    end
  end
end

app/controllers/api/cities_controller.rb
module Api
  class CitiesController < BaseController
    before_action :load_player

    def index
      @cities = @player.cities
    end

    def show
      @city = @player.cities.find params[:id]
    end

    def create
      @city = @player.cities.build city_params

      if @city.save
        render :show, status: :created, location: [:api, @player, @city]
      else
        render json: {errors: @city.errors}, status: :unprocessable_entity
      end
    end

    def update
      @city = @player.cities.find params[:id]

      if @city.update city_params
        render :show, location: [:api, @player, @city]
      else
        render json: {errors: @city.errors}, status: :unprocessable_entity
      end
    end

    def destroy
      @city = @player.cities.find params[:id]

      @city.destroy!
      render nothing: true, status: :no_content
    end

    private

    def load_player
      @player = Player.find params[:player_id]
    end

    def city_params
      params.require(:city).permit(:name, :acropolis, :x, :y,
                                   :timber_production, :bronze_production, :food_production,
                                   :timber_storage, :bronze_storage, :food_storage)
    end
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_player
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = @player.cities
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
    @raids = @city.raids.order(reported_at: :desc).decorate
    @scouts = @city.scouts.order(reported_at: :desc).decorate
  end

  # GET /cities/new
  def new
    @city = @player.cities.build
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = @player.cities.build(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to [@player, @city], notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: [@player, @city] }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to [@player, @city], notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: [@player, @city] }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to player_cities_url(@player), notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = @player.cities.find(params[:id])
    end

    def set_player
      @player = Player.find(params[:player_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:name, :acropolis, :level, :x, :y,
                                   :timber_production, :bronze_production, :food_production,
                                   :timber_storage, :bronze_storage, :food_storage)
    end
end

app/views/cities/_form.html.erb
<%= form_for([@player, @city], role: 'form') do |f| %>
  <% if @city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% @city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <%= label_tag :coordinates %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :x %>
        <%= f.number_field :x, class: 'form-control' %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :y %>
        <%= f.number_field :y, class: 'form-control' %>
      </div>
    </div>
  </div>
  <%= label_tag :production %>
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :timber_production, 'Timber' %>
        <%= f.number_field :timber_production, class: 'form-control' %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :bronze_production, 'Bronze' %>
        <%= f.number_field :bronze_production, class: 'form-control' %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :food_production, 'Food' %>
        <%= f.number_field :food_production, class: 'form-control' %>
      </div>
    </div>
  </div>
  <%= label_tag :storage %>
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :timber_storage, 'Timber' %>
        <%= f.number_field :timber_storage, class: 'form-control' %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :bronze_storage, 'Bronze' %>
        <%= f.number_field :bronze_storage, class: 'form-control' %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :food_storage, 'Food' %>
        <%= f.number_field :food_storage, class: 'form-control' %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :level %>
    <%= f.text_field :level, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :acropolis %>
    <%= f.number_field :acropolis, class: 'form-control' %>
  </div>
  <%= f.submit 'Save', class: 'btn btn-default' %>
  <small><%= link_to 'Cancel', player_path(@player) %></small>
<% end %>

app/views/cities/_table.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Cities
    <%= link_to 'New City', new_player_city_path(@player), class: 'btn btn-success pull-right' %>
    <div class="clearfix"></div>
  </div>
<table class="table table-condensed table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Level</th>
      <th>Acropolis</th>
      <th>Res Cap</th>
      <th>Storage</th>
      <th>Current</th>
      <th>Raid Estimate</th>
      <th>Last Report</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @cities.each do |city| %>
      <tr style="font-size: 13px;">
        <td><%= link_to city.name, [@player, city], title: "#{city.x}, #{city.y}", data: {toggle: 'tooltip'} %></td>
        <td><%= city.level.try(:to_i) || 'Not Set' %></td>
        <td><%= city.acropolis || 'Not Set' %></td>
        <td><%= city.resource_cap %></td>
        <td><%= city.timber_storage || '---' %> / <%= city.bronze_storage || '---' %> / <%= city.food_storage || '---' %></td>
        <td><%= city.current_resources(:timber) || '---' %> / <%= city.current_resources(:bronze) || '---' %> / <%= city.current_resources(:food) || '---' %></td>
        <td><%= city.estimated_raid_resources || '---' %></td>
        <% if city.scouts.any? or city.raids.any? %>
          <td><span class="time_ago" data-time="<%= city.last_battle_reported_at %>"></span></td>
        <% else %>
          <td>Never</td>
        <% end %>
        <td>
          <%= link_to icon('edit'), edit_player_city_path(@player, city) %>
        </td>
        <td>
          <%= link_to icon('delete'), [@player, city], method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
        <td>
          <%= link_to icon('scout'), [:new, @player, city, :scout], data: {toggle: 'modal', target: '#modal_form'} %>
        </td>
        <td>
          <%= link_to icon('raid'), [:new, @player, city, :raid], data: {toggle: 'modal', target: '#modal_form'} %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/cities/edit.html.erb
<%= form_wrapper 'Edit city', size: 'small' do %>
  <%= render 'form' %>
<% end %>

app/views/cities/index.html.erb
<h1>Listing cities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Resource Cap</th>
      <th>Total Resources</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td><%= city.name %></td>
        <td><%= "#{city.x}, #{city.y}" %></td>
        <td><%= 50000 - city.raids.last_week.map(&:total_resources).reduce(0, :+) %></td>
        <td><%= city.raids.map(&:total_resources).reduce(0, :+) %></td>
        <td><%= link_to 'Show', [@player, city] %></td>
        <td><%= link_to 'Edit', edit_player_city_path(@player, city) %></td>
        <td><%= link_to 'Destroy', [@player, city], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City', new_player_city_path(@player) %> |
<%= link_to 'Players', players_path %>

app/views/cities/new.html.erb
<%= form_wrapper 'New city', size: 'small' do %>
  <%= render 'form' %>
<% end %>

app/views/cities/show.html.erb
<%= link_to 'Back', player_path(@player) %>
<br />
<h2 class="sub-header">
  <%= @city.name %>
  <% if @city.level? %>
    <span class="text-muted">(<%= @city.level %>)</span>
  <% end %>
  <small>
    <%= link_to icon('edit'), edit_player_city_path(@player, @city) %>
  </small>
</h1>

<div class="row">
  <div class="col-md-6">
    <%= render 'raids/table' %>
  </div>
  <div class="col-md-6">
    <%= render 'scouts/table' %>
  </div>
</div>